
(()=>{'use strict';const $=id=>document.getElementById(id),ctx=$('board').getContext('2d');ctx.imageSmoothingEnabled=false;
const crew=[['Jak Stewart','jak-stewart-black-shirt'],['Cody Slack','cody-slack-black-shirt'],['Ash Kemp','ash-kemp-black-shirt'],['Matthew Heath','matthew-heath-black-shirt'],['Martyn Evans','martyn-evans'],['Luke Chambers','luke-chambers-black-shirt']];
const images=crew.map(([,f])=>{const im=new Image();im.src='driver-avatars/'+f+'.png';return im});let selected=0,state='menu',job=1,score=0,energy=3,player={x:7,y:10},tools=false,isolated=false,held=null,lastMove=0,lastFrame=0,sound=false,audio=null,sparks=[],panels=[],npcs=[],step=0,invincible=0,tasks={},snacks=new Set(),activityElapsed=0,resumeState='playing';
let best=0;try{best=Number(localStorage.getItem('spark_town_best_v1'))||0}catch{}$('best').textContent='Best score: '+best;
crew.forEach(([name],i)=>{const b=document.createElement('button');b.className='driver';b.setAttribute('aria-pressed',String(i===selected));const im=document.createElement('img');im.src=images[i].src;im.alt='';b.append(im,document.createTextNode(name));b.onclick=()=>{selected=i;Array.from($('roster').children).forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)))};$('roster').append(b)});
const buildings=[{x:1,y:1,w:4,h:3,label:'TOOL SHOP',roof:'#b5715c'},{x:10,y:1,w:4,h:3,label:'WORKSHOP',roof:'#557fa1'},{x:1,y:7,w:4,h:3,label:'DEPOT',roof:'#ba9a54'},{x:10,y:7,w:4,h:3,label:'CREW HOUSE',roof:'#8e6fa4'}];
function blocked(x,y){return x<1||x>13||y<1||y>11||buildings.some(b=>x>=b.x&&x<b.x+b.w&&y>=b.y&&y<b.y+b.h)||npcs.some(n=>n.x===x&&n.y===y)}
function beep(f=600){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.1)}catch{}}
function status(t){$('status').textContent=t}function hud(){$('level').textContent=String(job).padStart(2,'0');$('time').textContent=energy+' / 3';$('score').textContent=score}
function talk(name,text,done){held=null;state='dialogue';const d=$('dialogue');d.replaceChildren();const p=document.createElement('p');const strong=document.createElement('strong');strong.textContent=name+': ';p.append(strong,document.createTextNode(text));const b=document.createElement('button');b.textContent='Continue ▾';b.onclick=()=>{d.hidden=true;state='playing';if(done)done()};d.append(p,b);d.hidden=false;b.focus()}
function start(){energy=3;player={x:7,y:10};tools=false;isolated=false;tasks={van:false,fuse:false,socket:false,lunch:false};snacks=new Set();panels=[{x:9,y:3,name:'Fuse board',task:'fuse',done:false},{x:5,y:8,name:'Socket',task:'socket',done:false}];const spots=[[6,2],[11,5],[3,5],[8,6],[6,10],[12,10]];npcs=crew.map((c,i)=>({i,name:c[0],x:spots[i][0],y:spots[i][1]})).filter(n=>n.i!==selected);sparks=[{x:6,y:7,dir:1,t:0},{x:8,y:9,dir:-1,t:0}];state='playing';$('menu').hidden=true;$('dialogue').hidden=true;$('pause').disabled=false;status('Quest 1: pick up the tool kit outside the tool shop.');hud();updateJobs();talk('Martyn Evans','Morning! Fuse board, socket and van need sorting. Cody’s already asking what’s for lunch. Check your job list!')}
function near(x,y){return Math.abs(player.x-x)+Math.abs(player.y-y)<=1}
function completed(){status('Power restored! The crew has finished this job.');score+=300;best=Math.max(best,score);try{localStorage.setItem('spark_town_best_v1',String(best))}catch{}$('best').textContent='Best score: '+best;state='complete';$('menu-title').textContent='POWER RESTORED!';$('menu-desc').textContent=crew[selected][0]+' saved the day. '+score+' points! Ready for another job?';$('roster').hidden=true;$('menu-help').hidden=true;$('start').textContent='Next job';$('menu').hidden=false;$('pause').disabled=true;hud()}
const snackSpots=[{x:3,y:6,name:'Sandwich'},{x:12,y:6,name:'Crisps'},{x:8,y:2,name:'Chocolate'}];
const taskNames={van:'Clean the van',fuse:'Wire the fuse board',socket:'Connect the socket',lunch:"Cody’s snack run"};
function updateJobs(){$('job-list').textContent='Job list · '+Object.values(tasks).filter(Boolean).length+' / 4'}
function closeActivity(){$('activity').hidden=true;state='playing';held=null;status('Choose your next job, or explore and talk to the crew.');}
function activity(title,help){held=null;state='activity';activityElapsed=0;const d=$('activity');d.replaceChildren();d.hidden=false;$('dialogue').hidden=true;const head=document.createElement('div');head.className='activity-head';const h=document.createElement('h2');h.textContent=title;const b=document.createElement('button');b.textContent='Back to town';b.onclick=closeActivity;head.append(h,b);const p=document.createElement('p');p.className='hint';p.textContent=help;d.append(head,p);return d}
function finishTask(id,bonus=0){if(tasks[id])return;tasks[id]=true;score+=id==='lunch'?250:300;score+=bonus;const panel=panels.find(p=>p.task===id);if(panel)panel.done=true;closeActivity();hud();updateJobs();beep(1100);const left=Object.values(tasks).filter(v=>!v).length;talk(id==='lunch'?'Cody Slack':'Nice work!',id==='lunch'?'Sandwich, crisps AND chocolate? You absolute legend. I might need a second lunch later.':taskNames[id]+' complete! '+(bonus?'Speed bonus: '+bonus+' points. ':'')+(left?left+' jobs left.':'All jobs finished. Tea time!'),()=>{if(!left)completed();else status(left+' jobs left. Check your job list for directions.')})}
function jobList(){if(!['playing','activity'].includes(state))return;const d=activity('Today’s jobs','Pick a job for directions. Explore the town to start it.');const hints={van:'The white van is parked beside the depot, near the bottom-left of the square.',fuse:'Collect the tool kit and isolate the supply. The fuse board is beside the workshop, top-right.',socket:'Collect the tool kit and isolate the supply. The socket is beside the depot, bottom-left.',lunch:'Find the sandwich by Ash, crisps near Cody, and chocolate north of the fountain. Take them to Cody.'};for(const [id,name] of Object.entries(taskNames)){const b=document.createElement('button');b.className='task';b.textContent=(tasks[id]?'✓ ':'○ ')+name;const small=document.createElement('small');small.textContent=id==='lunch'?snacks.size+' / 3 snacks collected':tasks[id]?'Completed':'Tap for directions';b.append(small);b.onclick=()=>{closeActivity();talk(name,tasks[id]?'Already finished. Nice one!':hints[id])};d.append(b)}}$('job-list').onclick=jobList;
function cleanVan(){if(tasks.van){talk('Van','Spotless. Let’s see how long the crew keeps it that way.');return}const d=activity('VAN RESCUE','First clear the rubbish, then scrub every muddy patch. Finish within 45 seconds for a bonus.');const clock=document.createElement('p');clock.id='van-clock';clock.textContent='Bonus clock: 45s';d.append(clock);const count=document.createElement('p');count.textContent='Rubbish: 0 / 6';d.append(count);const row=document.createElement('div');row.className='rubbish';let cleared=0;['Cody’s crisp bag','Coffee cup','Cable offcuts','Sandwich wrapper','Dusty gloves','Chocolate wrapper'].forEach(name=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>{if(b.disabled)return;b.disabled=true;b.textContent='✓ Cleared';cleared++;count.textContent='Rubbish: '+cleared+' / 6';beep(650);if(cleared===6){row.remove();count.textContent='Scrubbed: 0 / 6';scrub()}};row.append(b)});d.append(row);
function scrub(){const scene=document.createElement('div');scene.className='van-scene';scene.innerHTML='<div class="van-body"></div><div class="van-wheel a"></div><div class="van-wheel b"></div>';let clean=0;[[17,42],[32,47],[47,39],[58,56],[25,60],[70,63]].forEach(([x,y],i)=>{const b=document.createElement('button');b.className='mud';b.style.left=x+'%';b.style.top=y+'%';b.setAttribute('aria-label','Scrub muddy patch '+(i+1));let rubs=0;b.textContent='3';b.onclick=()=>{rubs++;b.textContent=String(3-rubs);beep(350+rubs*130);if(rubs===3){b.disabled=true;b.classList.add('clean');b.textContent='✓';clean++;count.textContent='Scrubbed: '+clean+' / 6';if(clean===6)finishTask('van',Math.max(0,Math.floor(45-activityElapsed)*5))}};scene.append(b)});d.append(scene);const tip=document.createElement('p');tip.textContent='Tap each patch three times. Cody claims none of the wrappers are his.';d.append(tip)}}
function repair(panel){if(panel.task==='socket'){socketPuzzle();return}const d=activity('FUSE BOARD','Arcade puzzle: choose a breaker, then the circuit with the same symbol. Wire all four pairs.');const icons=['★','●','▲','◆'];const labels=['Workshop lights','Van charger','Kettle','Cody’s microwave'];const targets=[...icons].sort(()=>Math.random()-.5);const area=document.createElement('div');area.className='wiring';let chosen=null,done=0;const note=document.createElement('p');note.textContent='0 / 4 circuits connected';d.append(note);const sources=[];for(let i=0;i<4;i++){const left=document.createElement('button');left.textContent=icons[i]+' Breaker';left.setAttribute('aria-pressed','false');left.onclick=()=>{chosen=i;sources.forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)))};sources.push(left);const line=document.createElement('div');line.className='wire-line';const right=document.createElement('button');right.textContent=targets[i]+' '+labels[i];right.onclick=()=>{if(chosen===null){note.textContent='Choose a breaker on the left first.';return}if(icons[chosen]!==targets[i]){note.textContent='Wrong circuit! Match the symbols.';beep(180);return}sources[chosen].disabled=true;sources[chosen].classList.add('done');sources[chosen].setAttribute('aria-pressed','false');right.disabled=true;right.classList.add('done');line.style.background='#397551';chosen=null;done++;note.textContent=done+' / 4 circuits connected';beep(900);if(done===4)finishTask('fuse')};area.append(left,line,right)}d.append(area)}
function socketPuzzle(){const d=activity('SOCKET CONNECTION','Rotate the cable tiles to follow the arrows on the plan, then test the socket. Fictional puzzle symbols.');const glyphs=['↑','→','↓','←'];const target=Array.from({length:4},()=>Math.floor(Math.random()*4));const rotation=target.map(v=>(v+1+Math.floor(Math.random()*3))%4);const plan=document.createElement('p');plan.textContent='Plan: '+target.map(v=>glyphs[v]).join('  ');plan.style.fontSize='32px';d.append(plan);const row=document.createElement('div');row.className='connection';rotation.forEach((v,i)=>{const b=document.createElement('button');b.textContent=glyphs[v];b.setAttribute('aria-label','Rotate cable tile '+(i+1));b.onclick=()=>{rotation[i]=(rotation[i]+1)%4;b.textContent=glyphs[rotation[i]];beep(450)};row.append(b)});d.append(row);const note=document.createElement('p');note.textContent='Tap a tile to rotate it clockwise.';const test=document.createElement('button');test.textContent='Test socket';test.onclick=()=>{if(rotation.every((v,i)=>v===target[i]))finishTask('socket');else{note.textContent='No power yet! Match all four arrows to the plan.';beep(170)}};d.append(note,test)}
function crewTalk(n){if(n.i===4){energy=3;hud();talk(n.name,'Never underestimate a tea break. Sit down, have a brew, then tackle one job at a time. Energy topped up!');return}if(n.i===1){if(snacks.size===3&&!tasks.lunch){finishTask('lunch');return}talk(n.name,tasks.lunch?'That was a cracking lunch. Anyone know when dinner is?':'I’m absolutely starving. Bring me a sandwich, crisps and chocolate. '+snacks.size+' / 3 collected.');return}const tips=['Tool kit first. The fuse board and socket are waiting.','',"Someone’s left rubbish all over the van. Reckon Cody knows anything about it?",'The socket puzzle needs all four arrows lined up.','',"Check the job list. I’m betting Cody finishes lunch before you finish the van."];talk(n.name,tips[n.i])}
function action(){if(state!=='playing')return;if(!tools&&near(3,4)){tools=true;score+=50;hud();status('Tool kit collected. Isolate at the green supply switch.');talk('Tool kit','All packed. The supply switch is by the fountain.');return}if(near(7,4)&&!isolated){if(!tools){talk('Supply switch','You need your tool kit first.');return}isolated=true;score+=100;hud();talk('Supply isolated','Fuse board and socket puzzles are unlocked.');return}const snack=snackSpots.find((s,i)=>!snacks.has(i)&&near(s.x,s.y));if(snack){const i=snackSpots.indexOf(snack);snacks.add(i);beep(800);updateJobs();talk('Snack found',snack.name+' packed for Cody! '+snacks.size+' / 3 collected.',()=>{if(snacks.size===3&&selected===1)finishTask('lunch');else status(snacks.size===3?'Take the snacks to Cody, near the workshop.':'Keep an eye out for the other snacks.')});return}if(near(5,10)){cleanVan();return}const panel=panels.find(p=>!p.done&&near(p.x,p.y));if(panel){if(!isolated)talk('Repair panel','Collect the kit and isolate the supply first.');else repair(panel);return}const npc=npcs.find(n=>near(n.x,n.y));if(npc){crewTalk(npc);return}status('Find the van, blue repair boxes, snacks or crew. TALK / USE beside them.')}
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};function move(dir){if(state!=='playing')return;const [dx,dy]=dirs[dir],x=player.x+dx,y=player.y+dy;if(!blocked(x,y)){player={x,y};step++;collision()}}
function collision(){if(invincible>0||state!=='playing')return;if(sparks.some(s=>s.x===player.x&&s.y===player.y)){energy--;invincible=2;hud();beep(150);if(!energy){talk('Tea break','The crew brought you back to the square. Energy restored—your repairs are safe.',()=>{energy=3;player={x:7,y:10};hud()})}else status('Zap! Lost one energy. Avoid the wandering sparks.')}}
function pause(){if(['playing','activity'].includes(state)){resumeState=state;if(state==='activity')$('activity').hidden=true;state='paused';held=null;$('menu-title').textContent='TEA BREAK';$('menu-desc').textContent='Take your time. The town will wait.';$('roster').hidden=true;$('menu-help').hidden=true;$('start').textContent='Resume';$('menu').hidden=false}else if(state==='paused'){$('menu').hidden=true;state=resumeState;if(state==='activity')$('activity').hidden=false}}$('pause').onclick=pause;$('start').onclick=()=>{if(state==='paused'){pause();return}if(state==='complete')job++;else{job=1;score=0}start()};$('action').onclick=action;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));beep()};
const keys={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};document.addEventListener('keydown',e=>{if(state!=='playing')return;if(keys[e.key]){e.preventDefault();if(!e.repeat){held=keys[e.key];move(held);lastMove=performance.now()}}else if(e.code==='Space'){e.preventDefault();if(!e.repeat)action()}else if(e.key==='Escape')pause()});document.addEventListener('keyup',e=>{if(keys[e.key]===held)held=null});document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held=b.dataset.dir;move(held);lastMove=performance.now()});['pointerup','pointercancel','lostpointercapture'].forEach(t=>b.addEventListener(t,()=>held=null))});window.addEventListener('blur',()=>{held=null;if(['playing','activity'].includes(state))pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['playing','activity'].includes(state))pause()});
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}function tree(x,y){rect(x+13,y+22,7,10,'#79674b');rect(x+5,y+8,23,20,'#34765a');rect(x+9,y+2,16,20,'#469262');rect(x+12,y+5,7,4,'#75ae6a')}
function sprite(i,x,y,walk=false){x*=32;y*=32;rect(x+7,y+26,19,4,'#66875a');rect(x+10,y+19,13,9,'#171b24');rect(x+8,y+21,3,5,'#d9a787');rect(x+23,y+21,3,5,'#d9a787');rect(x+11,y+27,5,4,'#354c64');rect(x+19,y+27,5,4,'#354c64');if(walk&&step%2)rect(x+11,y+29,5,3,'#212c39');const im=images[i];if(im.complete&&im.naturalWidth)ctx.drawImage(im,im.width*.18,0,im.width*.64,im.height*.76,x+3,y-4,27,27);}
function draw(){for(let y=0;y<13;y++)for(let x=0;x<15;x++){rect(x*32,y*32,32,32,(x+y)%2?'#93bb75':'#9ac37c');if(x>=5&&x<=9||y>=4&&y<=6||y===10||y===11){rect(x*32,y*32,32,32,'#d5ca98');rect(x*32+5,y*32+6,3,2,'#bfb681')}else{rect(x*32+6,y*32+10,2,4,'#7aa866');rect(x*32+20,y*32+22,2,4,'#7aa866')}if(x===0||x===14||y===0||y===12)tree(x*32,y*32)}
for(const b of buildings){const x=b.x*32,y=b.y*32,w=b.w*32;rect(x+3,y+26,w-6,66,'#f0e1b9');rect(x,y+8,w,33,b.roof);rect(x+8,y,w-16,10,b.roof);rect(x+4,y+38,w-8,4,'#755f59');rect(x+18,y+52,23,22,'#628b96');rect(x+w-42,y+52,23,22,'#628b96');rect(x+49,y+61,28,32,'#725d4c');rect(x+54,y+65,17,21,'#9c8261');ctx.font='12px Pixel';ctx.fillStyle='#fff7dc';ctx.textAlign='center';ctx.fillText(b.label,x+w/2,y+29)}
rect(6*32+2,5*32,60,31,'#758f8f');rect(6*32+7,5*32+4,50,22,'#7eb5d0');rect(7*32-4,5*32-14,9,31,'#bdd9d2');rect(7*32-10,5*32-17,22,6,'#e5eee0');
if(!tools){rect(3*32+7,4*32+10,19,16,'#e4b651');rect(3*32+11,4*32+6,11,6,'#776745');rect(3*32+14,4*32+15,5,5,'#fff4b8')}
rect(7*32+9,4*32+5,17,22,isolated?'#5e8d70':'#395e58');rect(7*32+14,4*32+10,6,10,isolated?'#bce494':'#f8d06a');
for(const p of panels){rect(p.x*32+7,p.y*32+7,21,23,p.done?'#568c65':'#508eaf');rect(p.x*32+11,p.y*32+11,13,10,'#263f50');rect(p.x*32+14,p.y*32+14,5,5,p.done?'#b7e999':'#efd177')}
for(const n of npcs){sprite(n.i,n.x,n.y);ctx.fillStyle='#fff7d2';ctx.font='14px Pixel';ctx.textAlign='center';ctx.fillText('!',n.x*32+17,n.y*32-8)}
drawExtras();
for(const s of sparks){rect(s.x*32+14,s.y*32+7,8,11,'#e77955');rect(s.x*32+9,s.y*32+15,13,8,'#edb75a');rect(s.x*32+14,s.y*32+21,6,6,'#e77955')}
if(invincible<=0||Math.floor(invincible*10)%2)sprite(selected,player.x,player.y,true);}
function drawExtras(){const x=5*32,y=10*32;rect(x-18,y+3,43,22,'#eff1df');rect(x+11,y+5,11,10,'#729eaf');rect(x-12,y+22,9,8,'#334049');rect(x+13,y+22,9,8,'#334049');if(!tasks.van){rect(x-9,y+12,8,6,'#896447');rect(x+3,y+15,7,5,'#896447')}snackSpots.forEach((s,i)=>{if(snacks.has(i))return;const x=s.x*32+10,y=s.y*32+10;rect(x,y,14,13,['#e7bd73','#d6a657','#83533f'][i]);rect(x+3,y+4,8,3,['#94a564','#fff0a5','#ce9461'][i]);ctx.fillStyle='#fff8d4';ctx.font='13px Pixel';ctx.textAlign='center';ctx.fillText('SNACK',s.x*32+16,s.y*32+4)})}
function frame(now){const dt=Math.min(.05,(now-lastFrame)/1000||0);lastFrame=now;if(state==='activity'&&!document.hidden){activityElapsed+=dt;const clock=$('van-clock');if(clock)clock.textContent=activityElapsed<45?'Bonus clock: '+Math.ceil(45-activityElapsed)+'s':'Keep going! You can still finish the job.';}if(state==='playing'){invincible=Math.max(0,invincible-dt);if(held&&now-lastMove>170){move(held);lastMove=now}for(const s of sparks){s.t+=dt;if(s.t>Math.max(.4,.9-job*.07)){s.t=0;let x=s.x+s.dir;if(x<6||x>8){s.dir*=-1;x=s.x+s.dir}s.x=x}}collision()}draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();
