CREATE TABLE IF NOT EXISTS operations (seq INTEGER PRIMARY KEY AUTOINCREMENT, session TEXT NOT NULL, op_id TEXT NOT NULL, body TEXT NOT NULL, UNIQUE(session, op_id));
CREATE INDEX IF NOT EXISTS operations_session ON operations(session, seq);
CREATE TABLE IF NOT EXISTS pairs (code TEXT PRIMARY KEY, token TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS attempts (ip TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
